---
linters:
  FinalNewline:
    enabled: true
  HardCodedString:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  SelfClosingTag:
    enabled: false
  Rubocop:
    enabled: true
    only:
      - Layout/EndOfLine
      - Lint/LiteralAsCondition
      - Style/PercentLiteralDelimiters
