default: &default
  secret_key_base: "<%= ENV['SECRET_KEY_BASE'] || '123' %>"
  email_interceptor_recipients: "example_email_interceptor_recipients"

maps: &maps
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"

apis: &apis
  census_api_end_point: "example_census_api_end_point"
  census_api_institution_code: "example_census_api_institution_code"
  census_api_portal_name: "example_census_api_portal_name"
  census_api_user_code: "example_census_api_user_code"
  sms_end_point:  ""
  sms_username: "example_sms_username"
  sms_password: "example_sms_password"

http_basic_auth: &http_basic_auth
  http_basic_auth: true

development:
  http_basic_username: "dev"
  http_basic_password: "pass"
  <<: *default
  <<: *maps

test:
  <<: *default
  <<: *maps

staging:
  secret_key_base: "example_secret_key_base"
  server_name: "example_server_name"
  rollbar_server_token: "example_rollbar_server_token"
  http_basic_username: "example_http_basic_username"
  http_basic_password: "example_http_basic_password"
  managers_url: "example_managers_url"
  managers_application_key: "example_managers_application_key"
  <<: *default
  <<: *maps
  <<: *apis

preproduction:
  secret_key_base: "example_secret_key_base"
  server_name: "example_server_name"
  rollbar_server_token: "example_rollbar_server_token"
  http_basic_username: "example_http_basic_username"
  http_basic_password: "example_http_basic_password"
  managers_url: "example_managers_url"
  managers_application_key: "example_managers_application_key"
  twitter_key: "example_twitter_key"
  twitter_secret: "example_twitter_secret"
  facebook_key: "example_facebook_key"
  facebook_secret: "example_facebook_secret"
  google_oauth2_key: "example_google_oauth2_key"
  google_oauth2_secret: "example_google_oauth2_secret"
  <<: *maps
  <<: *apis

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  server_name: "example_server_name"
  rollbar_server_token: "example_rollbar_server_token"
  http_basic_username: "example_http_basic_username"
  http_basic_password: "example_http_basic_password"
  managers_url: "example_managers_url"
  managers_application_key: "example_managers_application_key"
  twitter_key: "example_twitter_key"
  twitter_secret: "example_twitter_secret"
  facebook_key: "example_facebook_key"
  facebook_secret: "example_facebook_secret"
  google_oauth2_key: "example_google_oauth2_key"
  google_oauth2_secret: "example_google_oauth2_secret"
  <<: *maps
  <<: *apis
